name: Check Labels

on:
  pull_request:
    branches:
    - master
    types:
    - opened
    - labeled
    - unlabeled
    - synchronize

jobs:
  check_labels:
    runs-on: ubuntu-22.04
    steps:
    - name: debug
      if: contains(github.event.pull_request.labels.*.name, 'debug')
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        env
        echo "$GITHUB_CONTEXT"
    - uses: smartlyio/check-versioning-action@v5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
