name: Ruby Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        ruby: [2.3.x, 2.4.x, 2.5.x, 2.6.x, 2.7.x]
  
    steps:
      - name: Set ruby version
        run: echo ::set-output name=RUBY_VERSION::$([ -n '${{ matrix.ruby }}' ] && echo '${{ matrix.ruby }}' || echo '2.7.x')
        id: ruby-version
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          ruby -e 'puts RUBY_VERSION' > .ruby-version
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec --format progress

  publish:
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      matrix:
        ruby: [2.6.x]

    steps:
      - name: Set ruby version
        run: echo ::set-output name=RUBY_VERSION::$([ -n '${{ matrix.ruby }}' ] && echo '${{ matrix.ruby }}' || echo '2.7.x')
        id: ruby-version
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          ruby -e 'puts RUBY_VERSION' > .ruby-version
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Configure gem token
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.GEM_HOST_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          printf -- "---\n:rubygems_api_key: Bearer ${RUBYGEMS_AUTH_TOKEN}\n" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
      - name: Build and publish gem
        run: |
          gem_push=yes rake build release:rubygem_push
          rm $HOME/.gem/credentials