name: Ruby Gem

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.3.x, 2.4.x, 2.5.x, 2.6.x]

    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Set up Ruby
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Publish to RubyGems
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p $HOME/.gem
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
      - uses: smartlyio/github-release-notes-action@v1.0.0
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
